/**
 * Supabase Generated Types
 * 
 * Auto-generated by Supabase MCP.
 * DO NOT EDIT MANUALLY - run `pnpm db:gen-types` to regenerate.
 * 
 * Generated: 2025-01-27
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "13.0.5"
  }
  public: {
    Tables: {
      mdm_entity_catalog: {
        Row: {
          created_at: string
          criticality: Database["public"]["Enums"]["criticality"] | null
          domain: string | null
          entity_id: string
          entity_name: string
          entity_type: Database["public"]["Enums"]["entity_type"]
          lifecycle_status:
          | Database["public"]["Enums"]["lifecycle_status"]
          | null
          system: string | null
          tenant_scope: string | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          criticality?: Database["public"]["Enums"]["criticality"] | null
          domain?: string | null
          entity_id: string
          entity_name: string
          entity_type: Database["public"]["Enums"]["entity_type"]
          lifecycle_status?:
          | Database["public"]["Enums"]["lifecycle_status"]
          | null
          system?: string | null
          tenant_scope?: string | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          criticality?: Database["public"]["Enums"]["criticality"] | null
          domain?: string | null
          entity_id?: string
          entity_name?: string
          entity_type?: Database["public"]["Enums"]["entity_type"]
          lifecycle_status?:
          | Database["public"]["Enums"]["lifecycle_status"]
          | null
          system?: string | null
          tenant_scope?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      mdm_global_metadata: {
        Row: {
          approval_required: boolean | null
          business_term: string
          calculation_logic: string | null
          canon_status: Database["public"]["Enums"]["canon_status"]
          classification: Database["public"]["Enums"]["classification"] | null
          common_misuses: Json | null
          compliance_tags: Json | null
          created_at: string
          created_by: string | null
          criticality: Database["public"]["Enums"]["criticality"] | null
          data_owner: string | null
          data_steward: string | null
          data_type_biz: Database["public"]["Enums"]["data_type_biz"] | null
          data_type_tech: string | null
          default_behaviour: string | null
          default_interpretation: string | null
          definition_full: string | null
          definition_short: string | null
          dict_id: string
          domain: string | null
          downstream_use: Json | null
          edge_cases: Json | null
          entity_group: string | null
          errors_if_wrong: string | null
          example_values: Json | null
          format_pattern: string | null
          is_bindable: boolean
          is_group: boolean
          last_certified: string | null
          nullability: boolean | null
          parent_dict_id: string | null
          precision: string | null
          recertification_due: string | null
          related_terms: Json | null
          source_of_truth: string | null
          synonyms: Json | null
          tags: Json | null
          technical_name: string
          updated_at: string
          updated_by: string | null
          upstream_src: string | null
          valid_values: Json | null
          version: string
        }
        Insert: {
          approval_required?: boolean | null
          business_term: string
          calculation_logic?: string | null
          canon_status: Database["public"]["Enums"]["canon_status"]
          classification?: Database["public"]["Enums"]["classification"] | null
          common_misuses?: Json | null
          compliance_tags?: Json | null
          created_at?: string
          created_by?: string | null
          criticality?: Database["public"]["Enums"]["criticality"] | null
          data_owner?: string | null
          data_steward?: string | null
          data_type_biz?: Database["public"]["Enums"]["data_type_biz"] | null
          data_type_tech?: string | null
          default_behaviour?: string | null
          default_interpretation?: string | null
          definition_full?: string | null
          definition_short?: string | null
          dict_id: string
          domain?: string | null
          downstream_use?: Json | null
          edge_cases?: Json | null
          entity_group?: string | null
          errors_if_wrong?: string | null
          example_values?: Json | null
          format_pattern?: string | null
          is_bindable?: boolean
          is_group?: boolean
          last_certified?: string | null
          nullability?: boolean | null
          parent_dict_id?: string | null
          precision?: string | null
          recertification_due?: string | null
          related_terms?: Json | null
          source_of_truth?: string | null
          synonyms?: Json | null
          tags?: Json | null
          technical_name: string
          updated_at?: string
          updated_by?: string | null
          upstream_src?: string | null
          valid_values?: Json | null
          version: string
        }
        Update: {
          approval_required?: boolean | null
          business_term?: string
          calculation_logic?: string | null
          canon_status?: Database["public"]["Enums"]["canon_status"]
          classification?: Database["public"]["Enums"]["classification"] | null
          common_misuses?: Json | null
          compliance_tags?: Json | null
          created_at?: string
          created_by?: string | null
          criticality?: Database["public"]["Enums"]["criticality"] | null
          data_owner?: string | null
          data_steward?: string | null
          data_type_biz?: Database["public"]["Enums"]["data_type_biz"] | null
          data_type_tech?: string | null
          default_behaviour?: string | null
          default_interpretation?: string | null
          definition_full?: string | null
          definition_short?: string | null
          dict_id?: string
          domain?: string | null
          downstream_use?: Json | null
          edge_cases?: Json | null
          entity_group?: string | null
          errors_if_wrong?: string | null
          example_values?: Json | null
          format_pattern?: string | null
          is_bindable?: boolean
          is_group?: boolean
          last_certified?: string | null
          nullability?: boolean | null
          parent_dict_id?: string | null
          precision?: string | null
          recertification_due?: string | null
          related_terms?: Json | null
          source_of_truth?: string | null
          synonyms?: Json | null
          tags?: Json | null
          technical_name?: string
          updated_at?: string
          updated_by?: string | null
          upstream_src?: string | null
          valid_values?: Json | null
          version?: string
        }
        Relationships: [
          {
            foreignKeyName: "mdm_global_metadata_parent_dict_id_fkey"
            columns: ["parent_dict_id"]
            isOneToOne: false
            referencedRelation: "mdm_global_metadata"
            referencedColumns: ["dict_id"]
          },
        ]
      }
      mdm_lineage_edges: {
        Row: {
          created_at: string
          edge_id: string
          frequency: string | null
          from_node_id: string
          last_observed_at: string | null
          metadata: Json | null
          relationship: Database["public"]["Enums"]["relationship_type"]
          to_node_id: string
        }
        Insert: {
          created_at?: string
          edge_id: string
          frequency?: string | null
          from_node_id: string
          last_observed_at?: string | null
          metadata?: Json | null
          relationship: Database["public"]["Enums"]["relationship_type"]
          to_node_id: string
        }
        Update: {
          created_at?: string
          edge_id?: string
          frequency?: string | null
          from_node_id?: string
          last_observed_at?: string | null
          metadata?: Json | null
          relationship?: Database["public"]["Enums"]["relationship_type"]
          to_node_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "mdm_lineage_edges_from_node_id_mdm_lineage_nodes_node_id_fk"
            columns: ["from_node_id"]
            isOneToOne: false
            referencedRelation: "mdm_lineage_nodes"
            referencedColumns: ["node_id"]
          },
          {
            foreignKeyName: "mdm_lineage_edges_to_node_id_mdm_lineage_nodes_node_id_fk"
            columns: ["to_node_id"]
            isOneToOne: false
            referencedRelation: "mdm_lineage_nodes"
            referencedColumns: ["node_id"]
          },
        ]
      }
      mdm_lineage_nodes: {
        Row: {
          created_at: string
          criticality: Database["public"]["Enums"]["criticality"] | null
          domain: string | null
          metadata: Json | null
          node_id: string
          node_name: string
          node_type: Database["public"]["Enums"]["node_type"]
          system: string | null
        }
        Insert: {
          created_at?: string
          criticality?: Database["public"]["Enums"]["criticality"] | null
          domain?: string | null
          metadata?: Json | null
          node_id: string
          node_name: string
          node_type: Database["public"]["Enums"]["node_type"]
          system?: string | null
        }
        Update: {
          created_at?: string
          criticality?: Database["public"]["Enums"]["criticality"] | null
          domain?: string | null
          metadata?: Json | null
          node_id?: string
          node_name?: string
          node_type?: Database["public"]["Enums"]["node_type"]
          system?: string | null
        }
        Relationships: []
      }
      mdm_metadata_mapping: {
        Row: {
          approval_status: Database["public"]["Enums"]["approval_status"] | null
          canonical_metadata_id: string
          confidence_score: number | null
          created_at: string
          local_entity: string
          local_field: string
          local_system: string
          mapping_id: string
          mapping_source: Database["public"]["Enums"]["mapping_source"] | null
          updated_at: string
        }
        Insert: {
          approval_status?:
          | Database["public"]["Enums"]["approval_status"]
          | null
          canonical_metadata_id: string
          confidence_score?: number | null
          created_at?: string
          local_entity: string
          local_field: string
          local_system: string
          mapping_id: string
          mapping_source?: Database["public"]["Enums"]["mapping_source"] | null
          updated_at?: string
        }
        Update: {
          approval_status?:
          | Database["public"]["Enums"]["approval_status"]
          | null
          canonical_metadata_id?: string
          confidence_score?: number | null
          created_at?: string
          local_entity?: string
          local_field?: string
          local_system?: string
          mapping_id?: string
          mapping_source?: Database["public"]["Enums"]["mapping_source"] | null
          updated_at?: string
        }
        Relationships: []
      }
      mdm_naming_policy: {
        Row: {
          allowed_actions: Json | null
          constraints: Json | null
          created_at: string
          policy_id: string
          tier: number
        }
        Insert: {
          allowed_actions?: Json | null
          constraints?: Json | null
          created_at?: string
          policy_id: string
          tier: number
        }
        Update: {
          allowed_actions?: Json | null
          constraints?: Json | null
          created_at?: string
          policy_id?: string
          tier?: number
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      get_current_tenant_id: { Args: never; Returns: string }
      get_path_tenant_id: { Args: { storage_path: string }; Returns: string }
      user_has_permission: {
        Args: { p_permission_code: string }
        Returns: boolean
      }
    }
    Enums: {
      approval_status: "pending" | "approved" | "rejected"
      canon_status:
      | "LOCKED"
      | "PENDING"
      | "DRAFT"
      | "UNTRUSTED"
      | "CONFLICT"
      | "ACTIVE"
      | "DEPRECATED"
      | "ARCHIVED"
      classification: "PUBLIC" | "INTERNAL" | "CONFIDENTIAL" | "RESTRICTED"
      criticality: "CRITICAL" | "HIGH" | "MEDIUM" | "LOW"
      data_type_biz:
      | "TEXT"
      | "NUMBER"
      | "MONEY"
      | "DATE"
      | "BOOLEAN"
      | "ENUM"
      | "ARRAY"
      | "OBJECT"
      entity_type:
      | "table"
      | "view"
      | "api"
      | "screen"
      | "report"
      | "master"
      | "transactional"
      | "reference"
      lifecycle_status: "draft" | "active" | "deprecated"
      mapping_source: "manual" | "ai-suggested"
      node_type:
      | "field"
      | "entity"
      | "table"
      | "cell"
      | "job"
      | "api"
      | "report"
      relationship_type:
      | "depends_on"
      | "produces"
      | "transforms"
      | "read"
      | "write"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
  | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
  | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
  ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
    DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
  : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
    DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
  ? R
  : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
    DefaultSchema["Views"])
  ? (DefaultSchema["Tables"] &
    DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
      Row: infer R
    }
  ? R
  : never
  : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
  | keyof DefaultSchema["Tables"]
  | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
  ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
  : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
    Insert: infer I
  }
  ? I
  : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
  ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
    Insert: infer I
  }
  ? I
  : never
  : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
  | keyof DefaultSchema["Tables"]
  | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
  ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
  : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
    Update: infer U
  }
  ? U
  : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
  ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
    Update: infer U
  }
  ? U
  : never
  : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
  | keyof DefaultSchema["Enums"]
  | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
  ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
  : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
  ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
  : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
  | keyof DefaultSchema["CompositeTypes"]
  | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
  ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
  : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
  ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
  : never

export const Constants = {
  public: {
    Enums: {
      approval_status: ["pending", "approved", "rejected"],
      canon_status: [
        "LOCKED",
        "PENDING",
        "DRAFT",
        "UNTRUSTED",
        "CONFLICT",
        "ACTIVE",
        "DEPRECATED",
        "ARCHIVED",
      ],
      classification: ["PUBLIC", "INTERNAL", "CONFIDENTIAL", "RESTRICTED"],
      criticality: ["CRITICAL", "HIGH", "MEDIUM", "LOW"],
      data_type_biz: [
        "TEXT",
        "NUMBER",
        "MONEY",
        "DATE",
        "BOOLEAN",
        "ENUM",
        "ARRAY",
        "OBJECT",
      ],
      entity_type: [
        "table",
        "view",
        "api",
        "screen",
        "report",
        "master",
        "transactional",
        "reference",
      ],
      lifecycle_status: ["draft", "active", "deprecated"],
      mapping_source: ["manual", "ai-suggested"],
      node_type: ["field", "entity", "table", "cell", "job", "api", "report"],
      relationship_type: [
        "depends_on",
        "produces",
        "transforms",
        "read",
        "write",
      ],
    },
  },
} as const
