-- ============================================================================
-- AP-01: Vendor Master Tables
-- Version: 1.0.0
-- 
-- Hardened for: 
--   - Concurrency (Optimistic Locking via version column)
--   - Immutability (Trigger blocks edits after approval)
--   - SoD (DB constraint: approved_by <> created_by)
--   - RLS (Row Level Security for tenant isolation)
--   - Audit Trail (All mutations logged)
-- ============================================================================

-- ============================================================================
-- 1. VENDORS TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS ap.vendors (
    -- =========================================================================
    -- IDENTITY
    -- =========================================================================
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id UUID NOT NULL, -- RLS: Tenant isolation required (non-negotiable)
    
    -- =========================================================================
    -- IDENTIFICATION
    -- =========================================================================
    vendor_code VARCHAR(50) NOT NULL,  -- Generated by K_SEQ
    legal_name TEXT NOT NULL,
    display_name TEXT,
    tax_id VARCHAR(50),
    registration_number VARCHAR(50),
    
    -- =========================================================================
    -- CLASSIFICATION
    -- =========================================================================
    country VARCHAR(3) NOT NULL,  -- ISO 3166-1 alpha-3
    currency_preference VARCHAR(3) NOT NULL DEFAULT 'USD',  -- ISO 4217
    vendor_category VARCHAR(50),
    risk_level VARCHAR(20) DEFAULT 'LOW' CHECK (risk_level IN ('LOW', 'MEDIUM', 'HIGH')),
    
    -- =========================================================================
    -- STATUS MACHINE
    -- Valid states: draft → submitted → approved → suspended → archived
    -- =========================================================================
    status VARCHAR(20) NOT NULL DEFAULT 'draft'
        CHECK (status IN ('draft', 'submitted', 'approved', 'suspended', 'archived')),
    
    -- =========================================================================
    -- PAYMENT TERMS
    -- =========================================================================
    default_payment_terms INTEGER DEFAULT 30,  -- Days
    default_bank_account_id UUID,  -- FK to ap.vendor_bank_accounts (deferred)
    
    -- =========================================================================
    -- RISK FLAGS
    -- =========================================================================
    is_blacklisted BOOLEAN DEFAULT FALSE,
    duplicate_bank_account_flag BOOLEAN DEFAULT FALSE,
    high_risk_category_flag BOOLEAN DEFAULT FALSE,
    
    -- =========================================================================
    -- ACTORS (Who performed actions)
    -- =========================================================================
    created_by UUID NOT NULL,
    approved_by UUID,
    approved_at TIMESTAMPTZ,
    
    -- =========================================================================
    -- CONCURRENCY
    -- =========================================================================
    version INTEGER DEFAULT 1,  -- Optimistic locking
    
    -- =========================================================================
    -- TIMESTAMPS
    -- =========================================================================
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    
    -- =========================================================================
    -- CONSTRAINTS
    -- =========================================================================
    CONSTRAINT uq_vendor_code_tenant UNIQUE (tenant_id, vendor_code),
    CONSTRAINT uq_vendor_tax_id_tenant UNIQUE (tenant_id, tax_id) WHERE tax_id IS NOT NULL,
    
    -- SoD Constraint: Approver must be different from creator
    CONSTRAINT chk_sod_approval CHECK (
        (status = 'approved' AND approved_by IS NOT NULL AND approved_by != created_by) OR
        (status != 'approved')
    )
);

COMMENT ON TABLE ap.vendors IS 
    'Vendor Master - Approved vendor registry to prevent phantom vendors';

COMMENT ON COLUMN ap.vendors.vendor_code IS 
    'Unique vendor identifier generated by K_SEQ (SequencePort)';

COMMENT ON COLUMN ap.vendors.status IS 
    'State machine: draft → submitted → approved → suspended → archived';

COMMENT ON COLUMN ap.vendors.version IS 
    'Optimistic locking version (incremented on each update)';

COMMENT ON CONSTRAINT chk_sod_approval ON ap.vendors IS 
    'Segregation of Duties: Approver must be different from creator';

-- ============================================================================
-- 2. INDEXES
-- ============================================================================

CREATE INDEX idx_vendors_tenant_status ON ap.vendors(tenant_id, status);
CREATE INDEX idx_vendors_tenant_code ON ap.vendors(tenant_id, vendor_code);
CREATE INDEX idx_vendors_tax_id ON ap.vendors(tenant_id, tax_id) WHERE tax_id IS NOT NULL;
CREATE INDEX idx_vendors_created_by ON ap.vendors(tenant_id, created_by);
CREATE INDEX idx_vendors_approved_by ON ap.vendors(tenant_id, approved_by) WHERE approved_by IS NOT NULL;

-- ============================================================================
-- COMPOSITE INDEXES (Performance Optimization)
-- For common filter combinations
-- ============================================================================

-- For filtering by status + category (common in vendor lists)
CREATE INDEX idx_vendors_tenant_status_category 
  ON ap.vendors(tenant_id, status, vendor_category) 
  WHERE vendor_category IS NOT NULL;

-- For filtering by status + risk_level (risk management queries)
CREATE INDEX idx_vendors_tenant_status_risk 
  ON ap.vendors(tenant_id, status, risk_level);

-- ============================================================================
-- PARTIAL INDEXES (Performance Optimization)
-- For status-filtered queries (smaller index, faster queries)
-- ============================================================================

-- For active vendors (approved, suspended) - most common query
CREATE INDEX idx_vendors_tenant_active 
  ON ap.vendors(tenant_id, created_at DESC) 
  WHERE status IN ('approved', 'suspended');

-- For pending approval queue
CREATE INDEX idx_vendors_tenant_pending 
  ON ap.vendors(tenant_id, created_at ASC) 
  WHERE status = 'submitted';

-- For draft vendors (user's own drafts)
CREATE INDEX idx_vendors_tenant_drafts 
  ON ap.vendors(tenant_id, created_by, created_at DESC) 
  WHERE status = 'draft';

-- ============================================================================
-- 3. IMMUTABILITY TRIGGER
-- Prevents modification of approved vendors (audit integrity)
-- ============================================================================

CREATE OR REPLACE FUNCTION ap.prevent_vendor_modification()
RETURNS TRIGGER AS $$
BEGIN
    -- Block UPDATE and DELETE for approved vendors
    IF OLD.status = 'approved' THEN
        RAISE EXCEPTION 'Cannot modify approved vendor. Status: %', OLD.status
            USING ERRCODE = 'P0001';
    END IF;
    
    -- For DELETE, return OLD
    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    
    -- For UPDATE, return NEW
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_immutable_approved_vendors ON ap.vendors;
CREATE TRIGGER trg_immutable_approved_vendors
BEFORE DELETE OR UPDATE ON ap.vendors
FOR EACH ROW
WHEN (OLD.status = 'approved')
EXECUTE FUNCTION ap.prevent_vendor_modification();

COMMENT ON FUNCTION ap.prevent_vendor_modification() IS 
    'Prevents modification of approved vendors (audit integrity)';

-- ============================================================================
-- 4. VERSION AUTO-INCREMENT TRIGGER
-- Implements optimistic locking by incrementing version on each update
-- ============================================================================

CREATE OR REPLACE FUNCTION ap.increment_vendor_version()
RETURNS TRIGGER AS $$
BEGIN
    -- Auto-increment version (client must send expected version in WHERE)
    NEW.version = OLD.version + 1;
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_vendor_version ON ap.vendors;
CREATE TRIGGER trg_vendor_version
BEFORE UPDATE ON ap.vendors
FOR EACH ROW
EXECUTE FUNCTION ap.increment_vendor_version();

COMMENT ON FUNCTION ap.increment_vendor_version() IS 
    'Auto-increments version for optimistic locking';

-- ============================================================================
-- 5. ROW LEVEL SECURITY (RLS) - Tenant Isolation (CONT_07 requirement)
-- Ensures no cross-tenant data access at database level
-- ============================================================================

ALTER TABLE ap.vendors ENABLE ROW LEVEL SECURITY;

-- Policy for vendors: only access own tenant's data
DROP POLICY IF EXISTS vendors_tenant_isolation ON ap.vendors;
CREATE POLICY vendors_tenant_isolation ON ap.vendors
    FOR ALL
    USING (tenant_id = COALESCE(
        NULLIF(current_setting('app.current_tenant_id', true), ''),
        tenant_id::text
    )::UUID);

COMMENT ON POLICY vendors_tenant_isolation ON ap.vendors IS 
    'Ensures vendors are only visible to their owning tenant';

-- ============================================================================
-- 6. SEQUENCE FOR VENDOR CODES
-- Generates unique, sequential vendor codes per tenant
-- ============================================================================

CREATE OR REPLACE FUNCTION ap.generate_vendor_code(p_tenant_id UUID)
RETURNS VARCHAR(50) AS $$
DECLARE
    v_sequence INTEGER;
    v_year INTEGER;
BEGIN
    v_year := EXTRACT(YEAR FROM CURRENT_DATE);
    
    -- Get next sequence number (tenant-isolated)
    SELECT COALESCE(MAX(
        CASE 
            WHEN vendor_code ~ '^VND-[0-9]{4}-[0-9]+$' 
            THEN CAST(SPLIT_PART(vendor_code, '-', 3) AS INTEGER)
            ELSE 0
        END
    ), 0) + 1
    INTO v_sequence
    FROM ap.vendors
    WHERE tenant_id = p_tenant_id
      AND vendor_code LIKE 'VND-' || v_year::TEXT || '-%';
    
    RETURN 'VND-' || v_year::TEXT || '-' || LPAD(v_sequence::TEXT, 5, '0');
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION ap.generate_vendor_code(UUID) IS 
    'Generates unique vendor code: VND-YYYY-NNNNN';

-- ============================================================================
-- 7. STATISTICS FOR QUERY PLANNER (Performance Optimization)
-- ============================================================================

-- Increase statistics targets for frequently filtered columns
ALTER TABLE ap.vendors ALTER COLUMN tenant_id SET STATISTICS 1000;
ALTER TABLE ap.vendors ALTER COLUMN status SET STATISTICS 500;
ALTER TABLE ap.vendors ALTER COLUMN vendor_category SET STATISTICS 500;

-- Analyze tables after creating indexes
ANALYZE ap.vendors;
