/**
 * Vendor Repository Port
 * 
 * Interface for vendor persistence operations.
 * Used by AP-01 Vendor Master Cell.
 * 
 * Anti-Gravity: This is a PORT, not an adapter.
 * It defines WHAT we need, not HOW it's implemented.
 */

// ============================================================================
// 1. TYPES
// ============================================================================

/**
 * Vendor status (state machine)
 */
export type VendorStatus =
  | 'draft'
  | 'submitted'
  | 'approved'
  | 'suspended'
  | 'archived';

/**
 * Risk level
 */
export type RiskLevel = 'LOW' | 'MEDIUM' | 'HIGH';

/**
 * Transaction context for transactional operations
 */
export interface TransactionContext {
  /** Database transaction handle */
  tx: unknown;
  /** Correlation ID for tracing */
  correlationId: string;
}

/**
 * Vendor entity
 */
export interface Vendor {
  id: string;
  tenantId: string;

  // Identification
  vendorCode: string;
  legalName: string;
  displayName?: string;
  taxId?: string;
  registrationNumber?: string;

  // Classification
  country: string; // ISO 3166-1 alpha-3
  currencyPreference: string; // ISO 4217
  vendorCategory?: string;
  riskLevel: RiskLevel;

  // Status Machine
  status: VendorStatus;

  // Payment Terms
  defaultPaymentTerms: number; // Days
  defaultBankAccountId?: string;

  // Risk Flags
  isBlacklisted: boolean;
  duplicateBankAccountFlag: boolean;
  highRiskCategoryFlag: boolean;

  // Audit
  createdBy: string;
  createdAt: Date;
  approvedBy?: string;
  approvedAt?: Date;
  version: number; // Optimistic locking
  updatedAt: Date;
}

/**
 * Vendor bank account entity
 */
export interface VendorBankAccount {
  id: string;
  vendorId: string;
  tenantId: string;

  // Bank Details
  bankName: string;
  accountNumber: string;
  accountName: string;
  routingNumber?: string;
  swiftCode?: string;
  iban?: string;
  currency: string;

  // Status
  isPrimary: boolean;
  isActive: boolean;

  // Change Control
  changeRequestStatus?: 'pending_approval' | 'approved' | 'rejected';
  changeRequestedBy?: string;
  changeRequestedAt?: Date;
  changeApprovedBy?: string;
  changeApprovedAt?: Date;

  // Audit
  createdBy: string;
  createdAt: Date;
  version: number;
  updatedAt: Date;
}

/**
 * Vendor creation input
 * Note: vendorCode is generated by database function, not provided
 */
export interface CreateVendorInput {
  tenantId: string;
  legalName: string;
  displayName?: string;
  taxId?: string;
  registrationNumber?: string;
  country: string;
  currencyPreference: string;
  vendorCategory?: string;
  riskLevel?: RiskLevel;
  defaultPaymentTerms?: number;
  createdBy: string;
}

/**
 * Vendor update input (draft only)
 */
export interface UpdateVendorInput {
  tenantId: string; // Required for RLS
  legalName?: string;
  displayName?: string;
  taxId?: string;
  registrationNumber?: string;
  country?: string;
  currencyPreference?: string;
  vendorCategory?: string;
  riskLevel?: RiskLevel;
  defaultPaymentTerms?: number;
}

/**
 * Vendor status update input
 */
export interface UpdateVendorStatusInput {
  tenantId: string; // Required for RLS
  status: VendorStatus;
  approvedBy?: string;
  approvedAt?: Date;
}

/**
 * Bank account creation input
 */
export interface CreateBankAccountInput {
  vendorId: string;
  tenantId: string;
  bankName: string;
  accountNumber: string;
  accountName: string;
  routingNumber?: string;
  swiftCode?: string;
  iban?: string;
  currency: string;
  isPrimary?: boolean;
  createdBy: string;
}

/**
 * Bank account change request input
 */
export interface RequestBankAccountChangeInput {
  bankAccountId: string;
  tenantId: string; // Required for RLS
  bankName?: string;
  accountNumber?: string;
  accountName?: string;
  routingNumber?: string;
  swiftCode?: string;
  iban?: string;
  currency?: string;
  requestedBy: string;
}

/**
 * Bank account change approval input
 */
export interface ApproveBankAccountChangeInput {
  bankAccountId: string;
  tenantId: string; // Required for RLS
  approvedBy: string;
  approvedAt: Date;
}

/**
 * Query filters for listing vendors
 */
export interface VendorQueryFilters {
  tenantId: string;
  status?: VendorStatus | VendorStatus[];
  vendorCategory?: string;
  riskLevel?: RiskLevel;
  isBlacklisted?: boolean;
  search?: string; // Search in legalName, displayName, vendorCode
  limit?: number;
  offset?: number;
}

// ============================================================================
// 2. PORT INTERFACE
// ============================================================================

export interface VendorRepositoryPort {
  /**
   * Execute operations within a transaction
   * 
   * @param callback - Function to execute within transaction
   * @returns Result of the callback
   */
  withTransaction<T>(
    callback: (txContext: TransactionContext) => Promise<T>
  ): Promise<T>;

  /**
   * Create a new vendor
   * 
   * @param input - Vendor creation data
   * @param txContext - Transaction context
   * @returns Created vendor with generated ID
   */
  create(
    input: CreateVendorInput,
    txContext: TransactionContext
  ): Promise<Vendor>;

  /**
   * Find vendor by ID (read-only)
   * 
   * @param id - Vendor ID
   * @param tenantId - Tenant ID (for RLS)
   * @returns Vendor or null if not found
   */
  findById(
    id: string,
    tenantId: string
  ): Promise<Vendor | null>;

  /**
   * Find vendor by ID with row lock (for update)
   * 
   * @param id - Vendor ID
   * @param tenantId - Tenant ID (for RLS)
   * @param txContext - Transaction context
   * @returns Vendor or null if not found
   */
  findByIdForUpdate(
    id: string,
    tenantId: string,
    txContext: TransactionContext
  ): Promise<Vendor | null>;

  /**
   * Find vendor by vendor code
   * 
   * @param vendorCode - Vendor code
   * @param tenantId - Tenant ID
   * @returns Vendor or null if not found
   */
  findByCode(
    vendorCode: string,
    tenantId: string
  ): Promise<Vendor | null>;

  /**
   * Update vendor (draft only)
   * 
   * @param id - Vendor ID
   * @param input - Update data
   * @param txContext - Transaction context
   * @returns Updated vendor
   */
  update(
    id: string,
    input: UpdateVendorInput,
    txContext: TransactionContext
  ): Promise<Vendor>;

  /**
   * Update vendor status
   * 
   * @param id - Vendor ID
   * @param input - Status update data
   * @param txContext - Transaction context
   * @returns Updated vendor
   */
  updateStatus(
    id: string,
    input: UpdateVendorStatusInput,
    txContext: TransactionContext
  ): Promise<Vendor>;

  /**
   * List vendors with filters
   * 
   * @param filters - Query filters
   * @returns Vendors and total count
   */
  list(filters: VendorQueryFilters): Promise<{
    vendors: Vendor[];
    total: number;
  }>;

  /**
   * Add bank account to vendor
   * 
   * @param input - Bank account creation data
   * @param txContext - Transaction context
   * @returns Created bank account
   */
  addBankAccount(
    input: CreateBankAccountInput,
    txContext: TransactionContext
  ): Promise<VendorBankAccount>;

  /**
   * Find bank account by ID
   * 
   * @param id - Bank account ID
   * @param tenantId - Tenant ID
   * @returns Bank account or null if not found
   */
  findBankAccountById(
    id: string,
    tenantId: string
  ): Promise<VendorBankAccount | null>;

  /**
   * Find bank account by ID with row lock (for update)
   * 
   * @param id - Bank account ID
   * @param tenantId - Tenant ID
   * @param txContext - Transaction context
   * @returns Bank account or null if not found
   */
  findBankAccountByIdForUpdate(
    id: string,
    tenantId: string,
    txContext: TransactionContext
  ): Promise<VendorBankAccount | null>;

  /**
   * List bank accounts for a vendor
   * 
   * @param vendorId - Vendor ID
   * @param tenantId - Tenant ID
   * @returns Bank accounts
   */
  listBankAccounts(
    vendorId: string,
    tenantId: string
  ): Promise<VendorBankAccount[]>;

  /**
   * Request bank account change
   * 
   * @param input - Change request data
   * @param txContext - Transaction context
   * @returns Updated bank account
   */
  requestBankAccountChange(
    input: RequestBankAccountChangeInput,
    txContext: TransactionContext
  ): Promise<VendorBankAccount>;

  /**
   * Approve bank account change
   * 
   * @param input - Approval data
   * @param txContext - Transaction context
   * @returns Updated bank account
   */
  approveBankAccountChange(
    input: ApproveBankAccountChangeInput,
    txContext: TransactionContext
  ): Promise<VendorBankAccount>;

  /**
   * Detect duplicate bank accounts (same account number + routing number)
   * 
   * @param accountNumber - Account number
   * @param routingNumber - Routing number (optional)
   * @param tenantId - Tenant ID
   * @param excludeVendorId - Exclude this vendor from check
   * @returns Array of vendor IDs with duplicate accounts
   */
  detectDuplicateBankAccounts(
    accountNumber: string,
    routingNumber: string | undefined,
    tenantId: string,
    excludeVendorId?: string
  ): Promise<string[]>;
}
